// Code generated by protoc-gen-go.
// source: api/portal.proto
// DO NOT EDIT!

/*
Package portal is a generated protocol buffer package.

It is generated from these files:
	api/portal.proto

It has these top-level messages:
	FileInfo
	Frame
	PutResponse
	GetRequest
*/
package portal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SessionStateType int32

const (
	SessionStateType_UNKNOWN SessionStateType = 0
	SessionStateType_WAIT    SessionStateType = 1
	SessionStateType_ACTIVE  SessionStateType = 2
	SessionStateType_CANCEL  SessionStateType = 3
)

var SessionStateType_name = map[int32]string{
	0: "UNKNOWN",
	1: "WAIT",
	2: "ACTIVE",
	3: "CANCEL",
}
var SessionStateType_value = map[string]int32{
	"UNKNOWN": 0,
	"WAIT":    1,
	"ACTIVE":  2,
	"CANCEL":  3,
}

func (x SessionStateType) String() string {
	return proto.EnumName(SessionStateType_name, int32(x))
}
func (SessionStateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FrameType int32

const (
	FrameType_PING   FrameType = 0
	FrameType_BEGIN  FrameType = 1
	FrameType_HEADER FrameType = 2
	FrameType_CHUNK  FrameType = 3
)

var FrameType_name = map[int32]string{
	0: "PING",
	1: "BEGIN",
	2: "HEADER",
	3: "CHUNK",
}
var FrameType_value = map[string]int32{
	"PING":   0,
	"BEGIN":  1,
	"HEADER": 2,
	"CHUNK":  3,
}

func (x FrameType) String() string {
	return proto.EnumName(FrameType_name, int32(x))
}
func (FrameType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FileInfo struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Size     int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Mode     uint32 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	Mimetype string `protobuf:"bytes,4,opt,name=mimetype" json:"mimetype,omitempty"`
	IsDir    bool   `protobuf:"varint,5,opt,name=isDir" json:"isDir,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Frame struct {
	Type FrameType `protobuf:"varint,1,opt,name=type,enum=portal.FrameType" json:"type,omitempty"`
	// type != BEGIN
	Id int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// type = HEADER
	FileInfo *FileInfo `protobuf:"bytes,3,opt,name=fileInfo" json:"fileInfo,omitempty"`
	// type = CHUNK
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Frame) GetFileInfo() *FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

type PutResponse struct {
	Type SessionStateType `protobuf:"varint,1,opt,name=type,enum=portal.SessionStateType" json:"type,omitempty"`
	// type = WAIT
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	// type = ACTIVE
	ReceiverIP string `protobuf:"bytes,3,opt,name=receiverIP" json:"receiverIP,omitempty"`
	// type = CANCEL
	Reason string `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*FileInfo)(nil), "portal.FileInfo")
	proto.RegisterType((*Frame)(nil), "portal.Frame")
	proto.RegisterType((*PutResponse)(nil), "portal.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "portal.GetRequest")
	proto.RegisterEnum("portal.SessionStateType", SessionStateType_name, SessionStateType_value)
	proto.RegisterEnum("portal.FrameType", FrameType_name, FrameType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Portal service

type PortalClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (Portal_PutClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Portal_GetClient, error)
}

type portalClient struct {
	cc *grpc.ClientConn
}

func NewPortalClient(cc *grpc.ClientConn) PortalClient {
	return &portalClient{cc}
}

func (c *portalClient) Put(ctx context.Context, opts ...grpc.CallOption) (Portal_PutClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Portal_serviceDesc.Streams[0], c.cc, "/portal.Portal/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &portalPutClient{stream}
	return x, nil
}

type Portal_PutClient interface {
	Send(*Frame) error
	Recv() (*PutResponse, error)
	grpc.ClientStream
}

type portalPutClient struct {
	grpc.ClientStream
}

func (x *portalPutClient) Send(m *Frame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portalPutClient) Recv() (*PutResponse, error) {
	m := new(PutResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portalClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Portal_GetClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Portal_serviceDesc.Streams[1], c.cc, "/portal.Portal/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &portalGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Portal_GetClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type portalGetClient struct {
	grpc.ClientStream
}

func (x *portalGetClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Portal service

type PortalServer interface {
	Put(Portal_PutServer) error
	Get(*GetRequest, Portal_GetServer) error
}

func RegisterPortalServer(s *grpc.Server, srv PortalServer) {
	s.RegisterService(&_Portal_serviceDesc, srv)
}

func _Portal_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortalServer).Put(&portalPutServer{stream})
}

type Portal_PutServer interface {
	Send(*PutResponse) error
	Recv() (*Frame, error)
	grpc.ServerStream
}

type portalPutServer struct {
	grpc.ServerStream
}

func (x *portalPutServer) Send(m *PutResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portalPutServer) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Portal_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortalServer).Get(m, &portalGetServer{stream})
}

type Portal_GetServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type portalGetServer struct {
	grpc.ServerStream
}

func (x *portalGetServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

var _Portal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portal.Portal",
	HandlerType: (*PortalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _Portal_Put_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _Portal_Get_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0xb3, 0x71, 0x62, 0xec, 0x09, 0xad, 0xcc, 0x80, 0x90, 0x95, 0x03, 0x42, 0x96, 0x90,
	0xaa, 0x0a, 0xb5, 0x55, 0x38, 0x70, 0x36, 0xa9, 0x9b, 0x5a, 0x20, 0x13, 0x6d, 0x03, 0x3d, 0x2f,
	0x64, 0x0a, 0x2b, 0x1a, 0xaf, 0xf1, 0x6e, 0x11, 0x70, 0xe2, 0xca, 0xbf, 0x66, 0xbd, 0x71, 0x5c,
	0x87, 0xdb, 0xcc, 0x9b, 0x9d, 0x97, 0x6f, 0x5e, 0x0c, 0x91, 0xa8, 0xe4, 0x69, 0xa5, 0x6a, 0x23,
	0x6e, 0x4f, 0xaa, 0x5a, 0x19, 0x85, 0xfe, 0xb6, 0x4b, 0x7e, 0x42, 0x70, 0x21, 0x6f, 0x29, 0x2f,
	0x6f, 0x14, 0x22, 0x8c, 0x2a, 0x61, 0xbe, 0xc6, 0xec, 0x39, 0x3b, 0x0a, 0xb9, 0xab, 0x1b, 0x4d,
	0xcb, 0xdf, 0x14, 0x0f, 0xad, 0xe6, 0x71, 0x57, 0x37, 0xda, 0x46, 0xad, 0x29, 0xf6, 0xac, 0x76,
	0xc0, 0x5d, 0x8d, 0x53, 0x08, 0x36, 0x72, 0x43, 0xe6, 0x57, 0x45, 0xf1, 0xc8, 0xed, 0x77, 0x3d,
	0x3e, 0x81, 0xb1, 0xd4, 0xe7, 0xb2, 0x8e, 0xc7, 0x76, 0x10, 0xf0, 0x6d, 0x93, 0xfc, 0x61, 0x30,
	0xbe, 0xa8, 0xc5, 0x86, 0xf0, 0x05, 0x8c, 0xdc, 0x5e, 0xf3, 0xbb, 0x87, 0xb3, 0x47, 0x27, 0x2d,
	0xa8, 0x1b, 0xae, 0xec, 0x80, 0xbb, 0x31, 0x1e, 0xc2, 0x50, 0xae, 0x5b, 0x10, 0x5b, 0xe1, 0x4b,
	0x08, 0x6e, 0x5a, 0x74, 0x87, 0x32, 0x99, 0x45, 0xdd, 0x6a, 0xab, 0xf3, 0xee, 0x45, 0x03, 0xbd,
	0x16, 0x46, 0x38, 0xb8, 0x87, 0xdc, 0xd5, 0xc9, 0x5f, 0x06, 0x93, 0xe5, 0x9d, 0xe1, 0xa4, 0x2b,
	0x55, 0x6a, 0xb2, 0x8e, 0x7d, 0x90, 0x78, 0xe7, 0x76, 0x45, 0x5a, 0x4b, 0x55, 0x5e, 0x19, 0x61,
	0xfa, 0x3c, 0xf6, 0x2c, 0xa3, 0xbe, 0x51, 0xe9, 0x90, 0x42, 0xbe, 0x6d, 0xf0, 0x19, 0x40, 0x4d,
	0x9f, 0x49, 0xfe, 0xa0, 0x3a, 0x5f, 0x3a, 0xae, 0x90, 0xf7, 0x14, 0x7c, 0x0a, 0x7e, 0x4d, 0x42,
	0xab, 0xb2, 0x8d, 0xa9, 0xed, 0x92, 0x04, 0x60, 0x41, 0x16, 0xe5, 0xfb, 0x1d, 0x69, 0x73, 0xef,
	0xcd, 0x7a, 0xde, 0xc7, 0x29, 0x44, 0xff, 0xb3, 0xe0, 0x04, 0x1e, 0x7c, 0x28, 0xde, 0x16, 0xef,
	0xaf, 0x8b, 0x68, 0x80, 0x01, 0x8c, 0xae, 0xd3, 0x7c, 0x15, 0x31, 0x04, 0xf0, 0xd3, 0xf9, 0x2a,
	0xff, 0x98, 0x45, 0xc3, 0xa6, 0x9e, 0xa7, 0xc5, 0x3c, 0x7b, 0x17, 0x79, 0xc7, 0xaf, 0x21, 0xec,
	0x72, 0x6d, 0x9e, 0x2f, 0xf3, 0x62, 0x61, 0x17, 0x43, 0x18, 0xbf, 0xc9, 0x16, 0x79, 0xb1, 0xdd,
	0xbc, 0xcc, 0xd2, 0xf3, 0x8c, 0xdb, 0x4d, 0x2b, 0xcf, 0x2f, 0xad, 0x7d, 0xe4, 0xcd, 0xbe, 0x80,
	0xbf, 0x74, 0x71, 0xe0, 0x29, 0x78, 0x36, 0x34, 0x3c, 0xd8, 0xfb, 0x9f, 0xa6, 0x8f, 0x77, 0x6d,
	0x2f, 0xd0, 0x64, 0x70, 0xc4, 0xce, 0x98, 0x8d, 0xd5, 0xb3, 0xa7, 0x21, 0xee, 0x5e, 0xdc, 0xdf,
	0x39, 0xdd, 0x37, 0x49, 0x06, 0x67, 0xec, 0x93, 0xef, 0x3e, 0xd0, 0x57, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0xa7, 0xba, 0xe0, 0xb4, 0x02, 0x00, 0x00,
}
